Qa8 1299
denispalkin/MLH pull request #1
Opened 2021-04-01 04:17 UTC by Alex-Mashchenko

2021-04-01 05:48 UTC, denispalkin requested changes

2021-04-01 05:48 UTC, denispalkin commented on test/extended/story.js
> +        browser.refresh();
Probably it's better to add `afterEach()` hook instead of doing `browser.refresh()` in every test.

2021-04-01 05:48 UTC, denispalkin commented on test/extended/story.js
> +    it('TC-090 Placeholder is correct', function () {
According to our spreadsheet, a placeholder has its own sub-suite. I think the placeholder should be put in a separate describe.

2021-04-01 05:48 UTC, denispalkin commented on test/extended/story.js
> +    it('TC-091 The field is a dropdown', function () {
According to our spreadsheet, TC-091 is the start of the positive sub-suite. I think all positive tests should be put in separate describe.

2021-04-01 05:48 UTC, denispalkin commented on test/extended/story.js
> +    it('TC-102 Type is not selected', function () {
According to our spreadsheet, this test related to a negative sub-suite. I think it should be wrapped in a separate describe.

2021-04-01 21:02 UTC, MariiaSosedova requested changes

2021-04-01 23:08 UTC, dalaran78 reviewed
In general, looks good.  Just fix the points from our collaborators.

2021-04-02 00:00 UTC, Alex-Mashchenko commented on test/extended/story.js
> +        browser.refresh();
Done

2021-04-02 00:00 UTC, Alex-Mashchenko commented on test/extended/story.js
> +    it('TC-090 Placeholder is correct', function () {
Done

2021-04-02 00:00 UTC, Alex-Mashchenko commented on test/extended/story.js
> +    it('TC-091 The field is a dropdown', function () {
Done

2021-04-02 00:01 UTC, Alex-Mashchenko commented on test/extended/story.js
> +    it('TC-102 Type is not selected', function () {
Done

2021-04-02 00:01 UTC, Alex-Mashchenko commented on test/extended/story.js
> +        browser.refresh();
Done

2021-04-02 00:02 UTC, Alex-Mashchenko commented on test/extended/story.js
> +        browser.refresh();
Done

2021-04-02 00:04 UTC, Alex-Mashchenko commented on test/extended/story.js
> +        browser.pause(2000);
Done, it was removed.

2021-04-02 00:08 UTC, Alex-Mashchenko commented on test/extended/story.js
> +import inputValues4 from '../../helpers/methods'
Done, it was removed.

2021-04-02 00:47 UTC, dalaran78 approved these changes
👍

2021-04-02 01:03 UTC, Alex-Mashchenko commented on test/extended/story.js
> +        $(sel.storyType).click();
Done

2021-04-02 01:05 UTC, MariiaSosedova approved these changes
All looks great!

2021-04-02 01:07 UTC, denispalkin approved these changes

2021-04-02 01:08 UTC, merged

2021-04-02 01:10 UTC, Alex-Mashchenko commented
All request done