Qa8 1295
denispalkin/MLH pull request #11
Opened 2021-04-03 04:19 UTC by Agarbathi

please review my code

2021-04-03 04:26 UTC, Agarbathi commented
I couldn't made authorization, that's why 5 commits here.

2021-04-03 05:00 UTC, dalaran78 approved these changes
Looks good, nice job!

2021-04-03 05:50 UTC, denispalkin requested changes

2021-04-03 05:50 UTC, denispalkin commented on data/selectors.js
>    "ageError": ".ant-form-item-explain-error",
Maybe we could combine two selectors into one? I already have that selector on line 17 but I want to do some refactoring, so it will be `.ant-form-item-explain-error`.
```suggestion
  "error": ".ant-form-item-explain-error",
```

2021-04-03 05:50 UTC, denispalkin commented on data/selectors.js
> +  "ageRequired": ".ant-form-item-explain-error",
Maybe we could combine two selectors into one? I already have that selector on line 17 but I want to do some refactoring, so it will be `.ant-form-item-explain-error`.
```suggestion
  "error": ".ant-form-item-explain-error",
```

2021-04-03 05:50 UTC, denispalkin commented on data/expected.json
>    "keyDown" : "123455",
Please delete extra spaces after keys in lines 25...30.

2021-04-03 19:35 UTC, Alex-Mashchenko requested changes

2021-04-03 19:35 UTC, Alex-Mashchenko commented on data/selectors.js
> +  "ageRequired": ".ant-form-item-explain-error",
Delete your code from 22 lines and use this.
![image](https://user-images.githubusercontent.com/80077934/113489351-93b48600-9478-11eb-9d75-6f2cdb685f15.png)

2021-04-04 00:02 UTC, Agarbathi commented on data/expected.json
>    "keyDown" : "123455",
Done

2021-04-04 00:02 UTC, Agarbathi commented on data/selectors.js
> +  "ageRequired": ".ant-form-item-explain-error",
Done

2021-04-04 00:02 UTC, Agarbathi commented on data/selectors.js
>    "ageError": ".ant-form-item-explain-error",
Done

2021-04-04 01:33 UTC, denispalkin approved these changes
LGTM! Merge!

2021-04-04 01:42 UTC, denispalkin commented
I'm merging as the administrator since Alex's change request was refactored.

2021-04-04 01:42 UTC, merged