added gender(TC-053 - TC-061)
denispalkin/MLH pull request #15
Opened 2021-04-06 22:45 UTC by andkr5150

2021-04-07 00:18 UTC, denispalkin commented on test/extended/gender.js
> +});
Please add a new empty line 64.

2021-04-07 00:25 UTC, dalaran78 requested changes

2021-04-07 00:25 UTC, dalaran78 commented on test/extended/gender.js
> +            let elem = $$(elements.requiredLabel)[0].isEnabled();
We are decided to don't use selector indexes any more.  Is it possible to refactor selectors in your code?

2021-04-07 00:25 UTC, dalaran78 commented on test/extended/gender.js
> +});
No new line at end of file

2021-04-07 00:43 UTC, denispalkin requested changes

2021-04-07 00:43 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
Буду писать по-русски, так понятнее. В тесте нет проверки, что she & it кнопки серые. А в ручных тестах именно так и написано.

2021-04-07 00:43 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
Нет проверки, что he & it кнопки серые.

2021-04-07 00:43 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
Нет проверки, что he & she кнопки серые.

2021-04-07 00:43 UTC, denispalkin commented on test/extended/gender.js
> +            !expect(elem).toBeChecked()
Тест не делает: 
- клик на she
- не проверяет, что she is blue (enabled)

2021-04-07 00:43 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toBeChecked()
Тест не делает:

- клик на he
- клик на it
- не проверяет, что it is blue (enabled)

2021-04-07 00:43 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toBeChecked()
Тест не делает:

- клик на she
- клик на it
- не проверяет, что it is blue (enabled)

2021-04-09 21:42 UTC, MariiaSosedova requested changes

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +import ext from '../../data/expected.json';
if you don't use it maybe be better to delete it? it's unnecessary line of code

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +import {age, gender, name, story} from "../../data/testData";
if you don't use other objects - delete it from the list

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +        it('TC-056_1 User can choose only one button at the time: if selected he', function () {
this test is the same as the 2 tests below, but code is different, not sure that this code checks the other button "she" & "it". Agree? 
** I understood, lol. Your tests 056_1, 056_2 and 056_3 is the same test - testing that user can choose only one button at the time. 
Maybe it will be better to put on the summary more details about it. For exp: "User can choose only one button at the time: "he" selected, "it"&"she" are not. 
And add this summary for all three tests? It will be more understandable.

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +        it('TC-056_2 User can choose only one button at the time: not selected she', function () {
"not selected she" in the summary is correct?
** see comment above

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +        it('TC-056_3 User can choose only one button at the time: not selected it', function () {
"not selected it" in the summary is correct? 
"User can choose only one button at the time" doesn't mean that "not selected it" )

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +        it('TC-057_2 User can choose only one button at the time: not selected he', function () {
the same - about summary

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +            $$(elements.radioButtons)[gender.he].click();
what if create method for switching the buttons? we can safe 6 line (2->1 in 6 tests) in this code with it? (the same about tests below)

2021-04-09 21:42 UTC, MariiaSosedova commented on test/extended/gender.js
> +
delete please empty line 117

2021-04-09 22:11 UTC, andkr5150 commented on test/extended/gender.js
> +import {age, gender, name, story} from "../../data/testData";
deleted

2021-04-09 22:18 UTC, andkr5150 commented on test/extended/gender.js
> +import ext from '../../data/expected.json';
deleted

2021-04-09 22:20 UTC, andkr5150 commented on test/extended/gender.js
> +        it('TC-056_1 User can choose only one button at the time: if selected he', function () {
I don't see what I need to do here, only rewrite the summary

2021-04-10 00:57 UTC, MariiaSosedova approved these changes

2021-04-10 01:39 UTC, denispalkin approved these changes
LGTM. Merge!

2021-04-10 02:25 UTC, merged