QA8-1289 add corner tests for image
denispalkin/MLH pull request #18
Opened 2021-04-07 18:47 UTC by Mykhaylyak

2021-04-07 18:54 UTC, MariiaSosedova requested changes

2021-04-07 18:54 UTC, MariiaSosedova commented on test/extended/image.js
> +    describe('Corner cases', function () {
add empty line before line 37

2021-04-07 18:54 UTC, MariiaSosedova commented on data/testData.js
> +  "default_1": '../../data/images/png-2.png',
let's rename it just "default1" without "_"?

2021-04-07 19:19 UTC, Mykhaylyak commented on test/extended/image.js
> +    describe('Corner cases', function () {
done

2021-04-07 19:20 UTC, Mykhaylyak commented on data/testData.js
> +  "default_1": '../../data/images/png-2.png',
done

2021-04-07 19:24 UTC, MariiaSosedova approved these changes

2021-04-08 03:00 UTC, andkr5150 approved these changes

2021-04-08 03:21 UTC, merged