Qa8 1292 anna
denispalkin/MLH pull request #21
Opened 2021-04-08 08:15 UTC by AnnaBondaruck

Please review! I still need to work on TC-181, TC-182.

2021-04-08 16:43 UTC, dalaran78 submitted a review, later dismissed

2021-04-08 16:43 UTC, dalaran78 commented on package-lock.json
> -  "name": "qa8-mlh",
No need to push package-lock.json file to main branch. It will affect to setup settings for all project.

2021-04-08 23:40 UTC, Alex-Mashchenko requested changes
Please re-upload your file here without package-lock.json.

2021-04-09 01:41 UTC, MariiaSosedova requested changes

2021-04-09 01:41 UTC, MariiaSosedova commented on helpers/methods.js
> +function createDispAfteReset (name, gender, age, story) {
Do we really need two function with the same body?
Maybe use only one of then, just need to rename it (exp. input4FieldsSubTryagain or something like that?)

2021-04-09 01:41 UTC, MariiaSosedova commented on test/extended/reset.js
> +    describe('Reset button placeholder = "Try again!"', function () {
please add the N of TC in accordance with the excel file

2021-04-09 01:41 UTC, MariiaSosedova commented on test/extended/reset.js
> +
please delete empty line

2021-04-09 01:41 UTC, MariiaSosedova commented on test/extended/reset.js
> +    afterEach('Refresh page', () => {
and here add empty line) - before line 41

2021-04-09 03:06 UTC, AnnaBondaruck commented on package-lock.json
> -  "name": "qa8-mlh",
Done

2021-04-09 17:23 UTC, closed without merging

2021-04-09 17:23 UTC, MariiaSosedova commented
this branch in not actual anymore. There is a new one with all changes