QA8-1543 add tests for viewing image in Story + split image file for 2 + add new method
denispalkin/MLH pull request #22
Opened 2021-04-09 05:04 UTC by MariiaSosedova

please check code

2021-04-09 17:34 UTC, Mykhaylyak approved these changes

2021-04-10 01:27 UTC, Alex-Mashchenko requested changes

2021-04-10 01:27 UTC, Alex-Mashchenko commented on test/extended/imagePositive.js
> +    describe('Positive cases', function () {
use empty line after [22]

2021-04-10 01:46 UTC, MariiaSosedova commented on test/extended/imagePositive.js
> +    describe('Positive cases', function () {
it's done

2021-04-10 01:53 UTC, Alex-Mashchenko approved these changes
Looks good.

2021-04-10 02:09 UTC, merged