Qa8 1556
denispalkin/MLH pull request #23
Opened 2021-04-09 15:46 UTC by AnnaBondaruck

- Added TC-181, TC-181a, TC-181b, TC-182, TC-182a, TC-182b to reset.js;
- Removed blank lines from reset.js;
- Deleted the duplicate function from methods.js;
- Added new line to expected.json

2021-04-09 17:06 UTC, MariiaSosedova requested changes

2021-04-09 17:06 UTC, MariiaSosedova commented on helpers/methods.js
> +function inputValues4Reset (name, gender, age, story) {
what of try to create this function without any arguments (function inputValues$Reset () )? And this function will be add all defaults values in input fields.
Just instead of lines 85 - 89 use the function inputValues4(name.default, gender.it, age.default, story.comedy). 
And in your tests TC-181 - TC-183 instead of  inputValues4Reset(name.default, gender.it, age.default, story.comedy) you can use function inputValues$Reset () . What do you think?

2021-04-10 01:08 UTC, Alex-Mashchenko commented on test/extended/reset.js
> +            let submitBtn = $(sel.submit).isEnabled();
> can you use here isDisabled instead of isEnabled?
We dont have isDisabled as element.

2021-04-10 01:21 UTC, Alex-Mashchenko approved these changes
just fix maria's comments

2021-04-10 19:28 UTC, AnnaBondaruck commented on helpers/methods.js
> +function inputValues4Reset (name, gender, age, story) {
I added to the inputValues4Reset lic for submit and click for try again

2021-04-10 19:28 UTC, AnnaBondaruck commented on test/extended/reset.js
> +    afterEach('Refresh page', () => {
done

2021-04-10 20:14 UTC, denispalkin approved these changes
LGTM. All tests have passed. Merge.

2021-04-10 20:45 UTC, AnnaBondaruck commented on helpers/methods.js
> +function inputValues4Reset (name, gender, age, story) {
done

2021-04-10 21:01 UTC, merged