QA8-1287 files refactored
denispalkin/MLH pull request #3
Opened 2021-04-01 06:21 UTC by denispalkin

2021-04-01 21:39 UTC, MariiaSosedova requested changes

2021-04-01 21:39 UTC, MariiaSosedova commented on test/extended/name.js
> +      const error = $(sel.error).isDisplayed();
Looks like these 2 lines use in other tests too but with different parameter of name. Maybe create a method for this or not?

2021-04-01 21:39 UTC, MariiaSosedova commented on test/extended/name.js
>          browser.keys('Backspace'); //deletes 21804
for these lines we should to have method like we did with Dima

2021-04-01 21:39 UTC, MariiaSosedova commented on test/extended/name.js
>          browser.keys('Backspace');
method

2021-04-01 22:59 UTC, dalaran78 requested changes
Need to separate Positive and Negative cases to the different files.

2021-04-01 22:59 UTC, dalaran78 commented on test/extended/name.js
>    });
190 lines in the code. No more than **150** Julia said. Could you separate Positive and Negative cases to the different files ?

2021-04-02 02:21 UTC, denispalkin commented on test/extended/name.js
> +      const error = $(sel.error).isDisplayed();
Will do

2021-04-02 02:22 UTC, denispalkin commented on test/extended/name.js
>          browser.keys('Backspace'); //deletes 21804
Will do

2021-04-02 02:22 UTC, denispalkin commented on test/extended/name.js
>          browser.keys('Backspace');
Will do

2021-04-02 02:24 UTC, denispalkin commented on test/extended/name.js
>    });
Ok. Will split if the number of lines will be over 200.

2021-04-02 02:24 UTC, MariiaSosedova approved these changes

2021-04-02 02:24 UTC, dalaran78 approved these changes

2021-04-02 02:33 UTC, MariiaSosedova approved these changes

2021-04-02 02:33 UTC, MariiaSosedova approved these changes

2021-04-02 02:33 UTC, MariiaSosedova approved these changes

2021-04-02 02:52 UTC, merged