QA8-1374 add from TC-053 to TC-061
denispalkin/MLH pull request #4
Opened 2021-04-01 07:24 UTC by andkr5150

2021-04-01 07:55 UTC, denispalkin requested changes

2021-04-01 07:55 UTC, denispalkin commented on test/extended/gender.js
> +    describe('Placeholder', function (){
The title of describe 'Placeholder' is wrong here. It's the start of "Positive cases".

2021-04-01 07:55 UTC, denispalkin commented on test/extended/gender.js
> +            const elem = $('.ant-radio-checked').isDisplayed();
Here and further `$('.ant-radio-checked')` is hardcoded, which is not good. It needs to be replaced with reference to the `selectors.js` file.

2021-04-01 07:55 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
I think the logic of this test is wrong. Our spreadsheet for expected result says: "she" and "it" are grey, meaning they should be disabled `isEnabled() === false`

2021-04-01 07:55 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
I think the logic of this test is wrong. Our spreadsheet for expected result says: "he" and "it" are grey, meaning they should be disabled isEnabled() === false

2021-04-01 07:55 UTC, denispalkin commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
I think the logic of this test is wrong. Our spreadsheet for expected result says: "he" and "she" are grey, meaning they should be disabled isEnabled() === false

2021-04-01 23:05 UTC, dalaran78 requested changes
Absolutely solidarity with our respected code keeper, master Denis :)

2021-04-01 23:05 UTC, dalaran78 commented on test/extended/gender.js
> +});
No new line in the end of file

2021-04-02 23:19 UTC, MariiaSosedova requested changes

2021-04-02 23:19 UTC, MariiaSosedova commented on test/extended/gender.js
> +            expect(elem).toEqual(true);
+ Hardcoding + for these actions you need to create a function on the methods.js

2021-04-02 23:19 UTC, MariiaSosedova commented on test/extended/gender.js
> +//        browser.pause(2000);
Does it really need here?

2021-04-03 02:03 UTC, closed without merging